export default {
  "a layer": "une couche",
  "neuron": "neurone",
  "inputs": "entrées",
  "self-attention": "auto-attention",
  "feed-forward": "feed-forward",
  "residual + norm": "résiduel + normalisation",
  "× dozens of blocks": "× des dizaines de blocs",
  "tokens": "tokens",
  "vectors": "vecteurs",
  "image · patches": "image · patchs",
  "the network →": "le réseau →",
  "p( next token )": "p( token suivant )",
  "temperature": "température",
  "prompt": "prompt",
  "prompt · read in one pass": "prompt · lu en une passe",
  "generating…": "génération…",
  "KV cache · keys + values": "cache KV · clés + valeurs",
  "KV cache grows by one each step": "le cache KV grandit d'un à chaque étape",
  "predict → sample → append → repeat": "prédire → échantillonner → ajouter → répéter",
  "recompute O(n²)": "recalcul O(n²)",
  "cached O(n)": "en cache O(n)",
  "sharp": "aiguisé",
  "mid": "moyen",
  "flat": "plat",
  "loss": "perte",
  "loss high": "perte élevée",
  "loss ↓ getting it right": "perte ↓ il y arrive",
  "loss high · just guessing": "perte élevée · il devine",
  "tokens seen": "tokens vus",
  "trillion": "mille milliards",
  "billion": "milliard",
  "million": "million",
  "data · compute · params →": "données · calcul · paramètres →",
  "base model": "modèle de base",
  "base model · continues, won't answer": "modèle de base · continue, ne répond pas",
  "reward model": "modèle de récompense",
  "reward model · the judge": "modèle de récompense · le juge",
  "preferred behaviour": "comportement préféré",
  "helpful answers": "réponses utiles",
  "the transformer core": "le cœur transformer",
  "router": "routeur",
  "20 experts · 1–2 active": "20 experts · 1–2 actifs",
  "attention · every token × every token": "attention · chaque token × chaque token",
  "2× tokens → 4× work": "2× tokens → 4× de calcul",
  "tokens →": "tokens →",
  "text": "texte",
  "image": "image",
  "audio": "audio",
  "one shared space": "un espace partagé",
  "problem": "problème",
  "dead end ✕": "impasse ✕",
  "answer": "réponse",
  "thinking budget": "budget de réflexion",
  "model": "modèle",
  "tool": "outil",
  "result": "résultat",
  "policy": "politique",
  "answer A": "réponse A",
  "answer B": "réponse B",
  "Embedding + Position": "Embedding + Position",
  "Masked Multi-Head Attention": "Attention multi-têtes masquée",
  "Add & Norm": "Add & Norm",
  "Feed Forward": "Feed Forward",
  "Linear": "Linear",
  "Softmax": "Softmax",
  "× N blocks": "× N blocs",
  "only looks back ←": "ne regarde qu'en arrière ←",
  "expand ×4 → project": "étendre ×4 → projeter",
  "residual: add the input back": "résiduel : rajouter l'entrée",
  "policy · the model": "politique · le modèle",
  "reward": "récompense",
  "group average": "moyenne du groupe",
  "reference model": "modèle de référence",
  "reward model · judge": "modèle de récompense · juge",
  "verify ✓ / ✗": "vérifier ✓ / ✗",
  "advantage = reward − average": "avantage = récompense − moyenne",
  "the model": "le modèle",
  "frozen weights": "poids figés",
  "vector database": "base vectorielle",
  "your question": "votre question",
  "nearest in meaning": "les plus proches par le sens",
  "retrieved": "récupérés",
  "context window": "fenêtre de contexte",
  "grounded answer": "réponse ancrée",
  "hallucination?": "hallucination ?",
}
