export default {
  "a layer": "una capa",
  "neuron": "neurona",
  "inputs": "entradas",
  "self-attention": "autoatención",
  "feed-forward": "feed-forward",
  "residual + norm": "residual + norma",
  "× dozens of blocks": "× decenas de bloques",
  "tokens": "tokens",
  "vectors": "vectores",
  "image · patches": "imagen · parches",
  "the network →": "la red →",
  "p( next token )": "p( siguiente token )",
  "temperature": "temperatura",
  "prompt": "prompt",
  "prompt · read in one pass": "prompt · leído en una pasada",
  "generating…": "generando…",
  "KV cache · keys + values": "caché KV · claves + valores",
  "KV cache grows by one each step": "la caché KV crece en uno por paso",
  "predict → sample → append → repeat": "predecir → muestrear → añadir → repetir",
  "recompute O(n²)": "recalcular O(n²)",
  "cached O(n)": "en caché O(n)",
  "sharp": "agudo",
  "mid": "medio",
  "flat": "plano",
  "loss": "pérdida",
  "loss high": "pérdida alta",
  "loss ↓ getting it right": "pérdida ↓ acertando",
  "loss high · just guessing": "pérdida alta · solo conjeturando",
  "tokens seen": "tokens vistos",
  "trillion": "billón",
  "billion": "mil millones",
  "million": "millón",
  "data · compute · params →": "datos · cómputo · parámetros →",
  "base model": "modelo base",
  "base model · continues, won't answer": "modelo base · continúa, no responde",
  "reward model": "modelo de recompensa",
  "reward model · the judge": "modelo de recompensa · el juez",
  "preferred behaviour": "comportamiento preferido",
  "helpful answers": "respuestas útiles",
  "the transformer core": "el núcleo Transformer",
  "router": "enrutador",
  "20 experts · 1–2 active": "20 expertos · 1–2 activos",
  "attention · every token × every token": "atención · cada token × cada token",
  "2× tokens → 4× work": "2× tokens → 4× trabajo",
  "tokens →": "tokens →",
  "text": "texto",
  "image": "imagen",
  "audio": "audio",
  "one shared space": "un espacio compartido",
  "problem": "problema",
  "dead end ✕": "callejón sin salida ✕",
  "answer": "respuesta",
  "thinking budget": "presupuesto de pensamiento",
  "model": "modelo",
  "tool": "herramienta",
  "result": "resultado",
  "policy": "política",
  "answer A": "respuesta A",
  "answer B": "respuesta B",
  "Embedding + Position": "Embedding + Posición",
  "Masked Multi-Head Attention": "Atención multi-cabezal enmascarada",
  "Add & Norm": "Add & Norm",
  "Feed Forward": "Feed Forward",
  "Linear": "Linear",
  "Softmax": "Softmax",
  "× N blocks": "× N bloques",
  "only looks back ←": "solo mira atrás ←",
  "expand ×4 → project": "expandir ×4 → proyectar",
  "residual: add the input back": "residual: vuelve a sumar la entrada",
  "policy · the model": "política · el modelo",
  "reward": "recompensa",
  "group average": "promedio del grupo",
  "reference model": "modelo de referencia",
  "reward model · judge": "modelo de recompensa · juez",
  "verify ✓ / ✗": "verificar ✓ / ✗",
  "advantage = reward − average": "ventaja = recompensa − promedio",
  "the model": "el modelo",
  "frozen weights": "pesos congelados",
  "vector database": "base de datos vectorial",
  "your question": "tu pregunta",
  "nearest in meaning": "más cercanos en significado",
  "retrieved": "recuperados",
  "context window": "ventana de contexto",
  "grounded answer": "respuesta fundamentada",
  "hallucination?": "¿alucinación?",
}
