export default {
  "a layer": "طبقة",
  "neuron": "خلية عصبية",
  "inputs": "مدخلات",
  "self-attention": "الانتباه الذاتي",
  "feed-forward": "التغذية الأمامية",
  "residual + norm": "متبقٍّ + تطبيع",
  "× dozens of blocks": "× عشرات الكتل",
  "tokens": "رموز",
  "vectors": "متجهات",
  "image · patches": "صورة · رقع",
  "the network →": "الشبكة →",
  "p( next token )": "p( الرمز التالي )",
  "temperature": "درجة الحرارة",
  "prompt": "المُوجِّه",
  "prompt · read in one pass": "المُوجِّه · يُقرأ في تمريرة واحدة",
  "generating…": "جارٍ التوليد…",
  "KV cache · keys + values": "ذاكرة KV · مفاتيح + قيم",
  "KV cache grows by one each step": "ذاكرة KV تنمو بمقدار واحد كل خطوة",
  "predict → sample → append → repeat": "تنبّأ → اسحب عيّنة → ألحِق → كرّر",
  "recompute O(n²)": "إعادة الحساب O(n²)",
  "cached O(n)": "مخزَّن مؤقتًا O(n)",
  "sharp": "حادّ",
  "mid": "متوسّط",
  "flat": "مسطّح",
  "loss": "خسارة",
  "loss high": "خسارة عالية",
  "loss ↓ getting it right": "خسارة ↓ يُصيب الهدف",
  "loss high · just guessing": "خسارة عالية · مجرّد تخمين",
  "tokens seen": "رموز مُشاهَدة",
  "trillion": "تريليون",
  "billion": "مليار",
  "million": "مليون",
  "data · compute · params →": "بيانات · حوسبة · معاملات →",
  "base model": "نموذج أساس",
  "base model · continues, won't answer": "نموذج أساس · يُكمل، لا يجيب",
  "reward model": "نموذج المكافأة",
  "reward model · the judge": "نموذج المكافأة · الحَكَم",
  "preferred behaviour": "سلوك مفضّل",
  "helpful answers": "إجابات مفيدة",
  "the transformer core": "نواة المحوّل",
  "router": "موجِّه",
  "20 experts · 1–2 active": "20 خبيرًا · 1–2 نشط",
  "attention · every token × every token": "الانتباه · كل رمز × كل رمز",
  "2× tokens → 4× work": "2× رموز → 4× عمل",
  "tokens →": "رموز →",
  "text": "نص",
  "image": "صورة",
  "audio": "صوت",
  "one shared space": "فضاء مشترك واحد",
  "problem": "مسألة",
  "dead end ✕": "طريق مسدود ✕",
  "answer": "إجابة",
  "thinking budget": "ميزانية التفكير",
  "model": "نموذج",
  "tool": "أداة",
  "result": "نتيجة",
  "policy": "سياسة",
  "answer A": "إجابة A",
  "answer B": "إجابة B",
  "Embedding + Position": "التضمين + الموضع",
  "Masked Multi-Head Attention": "الانتباه متعدّد الرؤوس المُقنَّع",
  "Add & Norm": "الجمع والتطبيع",
  "Feed Forward": "التغذية الأمامية",
  "Linear": "خطّي",
  "Softmax": "softmax",
  "× N blocks": "× N كتلة",
  "only looks back ←": "ينظر إلى الخلف فقط ←",
  "expand ×4 → project": "توسيع ×4 → إسقاط",
  "residual: add the input back": "متبقٍّ: أضِف المدخل ثانيةً",
  "policy · the model": "السياسة · النموذج",
  "reward": "مكافأة",
  "group average": "متوسّط المجموعة",
  "reference model": "النموذج المرجعي",
  "reward model · judge": "نموذج المكافأة · حَكَم",
  "verify ✓ / ✗": "تحقّق ✓ / ✗",
  "advantage = reward − average": "الأفضليّة = المكافأة − المتوسّط",
  "the model": "النموذج",
  "frozen weights": "أوزان مجمّدة",
  "vector database": "قاعدة بيانات متجهة",
  "your question": "سؤالك",
  "nearest in meaning": "الأقرب في المعنى",
  "retrieved": "المُسترجَع",
  "context window": "نافذة السياق",
  "grounded answer": "إجابة مستندة",
  "hallucination?": "هلوسة؟",
}
