export default {
  "a layer": "一层",
  "neuron": "神经元",
  "inputs": "输入",
  "self-attention": "自注意力",
  "feed-forward": "前馈",
  "residual + norm": "残差 + 归一化",
  "× dozens of blocks": "× 几十个区块",
  "tokens": "词元",
  "vectors": "向量",
  "image · patches": "图像 · 图块",
  "the network →": "网络 →",
  "p( next token )": "p( 下一个词元 )",
  "temperature": "温度",
  "prompt": "提示词",
  "prompt · read in one pass": "提示词 · 一次读完",
  "generating…": "生成中…",
  "KV cache · keys + values": "KV 缓存 · 键 + 值",
  "KV cache grows by one each step": "KV 缓存每步加一列",
  "predict → sample → append → repeat": "预测 → 采样 → 追加 → 重复",
  "recompute O(n²)": "重算 O(n²)",
  "cached O(n)": "缓存 O(n)",
  "sharp": "尖锐",
  "mid": "适中",
  "flat": "平坦",
  "loss": "损失",
  "loss high": "损失高",
  "loss ↓ getting it right": "损失 ↓ 答对了",
  "loss high · just guessing": "损失高 · 只是瞎猜",
  "tokens seen": "已见词元",
  "trillion": "万亿",
  "billion": "十亿",
  "million": "百万",
  "data · compute · params →": "数据 · 算力 · 参数 →",
  "base model": "基础模型",
  "base model · continues, won't answer": "基础模型 · 续写,不作答",
  "reward model": "奖励模型",
  "reward model · the judge": "奖励模型 · 裁判",
  "preferred behaviour": "偏好的行为",
  "helpful answers": "有用的回答",
  "the transformer core": "Transformer 核心",
  "router": "路由器",
  "20 experts · 1–2 active": "20 个专家 · 1–2 个活跃",
  "attention · every token × every token": "注意力 · 每个词元 × 每个词元",
  "2× tokens → 4× work": "2× 词元 → 4× 计算量",
  "tokens →": "词元 →",
  "text": "文本",
  "image": "图像",
  "audio": "音频",
  "one shared space": "一个共享空间",
  "problem": "问题",
  "dead end ✕": "死胡同 ✕",
  "answer": "答案",
  "thinking budget": "思考预算",
  "model": "模型",
  "tool": "工具",
  "result": "结果",
  "policy": "策略",
  "answer A": "回答 A",
  "answer B": "回答 B",
  "Embedding + Position": "嵌入 + 位置",
  "Masked Multi-Head Attention": "掩码多头注意力",
  "Add & Norm": "残差 + 归一化",
  "Feed Forward": "前馈",
  "Linear": "线性",
  "Softmax": "Softmax",
  "× N blocks": "× N 个区块",
  "only looks back ←": "只回看 ←",
  "expand ×4 → project": "扩展 ×4 → 投影",
  "residual: add the input back": "残差:把输入加回来",
  "policy · the model": "策略 · 模型",
  "reward": "奖励",
  "group average": "组平均值",
  "reference model": "参考模型",
  "reward model · judge": "奖励模型 · 裁判",
  "verify ✓ / ✗": "验证 ✓ / ✗",
  "advantage = reward − average": "优势 = 奖励 − 平均值",
  "the model": "模型",
  "frozen weights": "冻结的权重",
  "vector database": "向量数据库",
  "your question": "你的问题",
  "nearest in meaning": "语义最相近",
  "retrieved": "已检索",
  "context window": "上下文窗口",
  "grounded answer": "有依据的回答",
  "hallucination?": "幻觉?",
}
